#!/bin/bash
while true
do
clear
echo "================================="
echo "POCKET SOC MOBILE v1.6.2 👑"
echo "King Vasco"
echo "================================="
echo "1. Logwatcher"
echo "2. Portscanner"
echo "3. View Report"
echo "4. Dashboard"
echo "5. Threat Intel"
echo "6. Exit"
echo "================================="
read -p "Select: " choice

if [ "$choice" == "1" ]; then
    bash logwatcher.sh
elif [ "$choice" == "2" ]; then
    bash portscanner.sh
elif [ "$choice" == "3" ]; then
    cat report.csv
    read -p "Press Enter to continue"
elif [ "$choice" == "4" ]; then
    ls dashboard/
    read -p "Press Enter to continue"
elif [ "$choice" == "5" ]; then
    echo "Enter IP to investigate: "
    read ip
    python investigate.py $ip
    read -p "Press Enter to continue"
elif [ "$choice" == "6" ]; then
    echo "Bye 👑"
    exit
else
    echo "Invalid option"
    sleep 2
fi
done
